---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-deployment
  labels:
    app: {{ .Release.Name }}-redis-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
      - name: {{ .Release.Name }}-redis-app
        image: {{ .Values.containers.redis }}
        ports:
        - containerPort: 6379
