---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client-deployment
  labels:
    app: {{ .Release.Name }}-client-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
    spec:
      containers:
      - name: {{ .Release.Name }}-client-app
        image: {{ .Values.containers.client }}
        ports:
        - containerPort: 4200
