apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hosts

spec:
  rules:
  - host: api.lab.vandergizer.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
           service:
            name: {{ .Release.Name }}-api-service
            port:
              number: 4000

  - host: ez.lab.vandergizer.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
           service:
            name: {{ .Release.Name }}-client-service
            port:
              number: 80

  - host: legal.lab.vandergizer.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
           service:
            name: {{ .Release.Name }}-legal-service
            port:
              number: 80
