---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  labels:
    owner: DaniilT
spec:
  selector:
    app: {{ .Release.Name }}-api  # Selecting PODS with those Labels
  ports:
    - name      : {{ .Release.Name }}-api-listener
      protocol  : TCP
      port      : 4000  # Port on Load Balancer
      targetPort: 4000  # Port on POD
  type: LoadBalancer
