---
- name: Install epel-release
  yum:
      name: epel-release
      state: latest
      update_cache: true

- name: Install nginx
  yum:
      name: nginx
      state: latest
      update_cache: true

- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Remove nginx.conf
  ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent
  register: delete

- name: copy new nginx.conf file
  ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx
  when: delete.changed
  notify: restart nginx
  
- name: Start nginx
  service: name=nginx state=started enabled=yes
