---
- name: copy sql dump file
  ansible.builtin.copy:
    src: table.sql
    dest: /home/dan

- name: Ensure MySQL databases are present.
  mysql_db:
    name: "{{ new_mysql_db_name }}"
    collation: latin1_general_ci
    encoding: latin1
    state: import
    target: /home/dan/table.sql
