---
- name: Ensure MySQL users are present.
  mysql_user:
    name: "{{ new_mysql_user_name }}"
    host: "%"
    password: "{{ new_mysql_user_pass }}"
    priv: "{{ new_mysql_db_name }}.*:ALL"
    state: 'present'
    append_privs: 'no'
    encrypted: 'no'
  no_log: true
