---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  db_name : {{ .Values.db_name }}
  username: {{ .Values.username }}
  password: {{ .Values.password }}
  endpoint: {{ .Values.endpoint }}
