---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  db_name : {{ .Values.db_name | quote }}
  username: {{ .Values.username | quote }}
  password: {{ .Values.password | quote }}
  endpoint: {{ .Values.endpoint | quote }}
