mysql_root_password: root1234
mysql_databases:
  - name: example_db
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: admin
    host: "%"
    password: 1234
    priv: "example_db.*:ALL"
