---
- name: Install epel-release
  yum:
      name: epel-release
      state: latest
      update_cache: true

- name: Install nginx
  yum:
      name: nginx
      state: latest
      update_cache: true

- name: Open http port
  ansible.builtin.shell: firewall-cmd --zone=public --permanent --add-service=http
  register: firewall

- name: Reload firewall
  ansible.builtin.shell: firewall-cmd --reload
  when: firewall.changed

- name: Remove nginx.conf
  ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent
  register: delete

- name: copy new nginx.conf file
  ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx
  when: delete.changed
  notify: restart nginx
  
- name: Start nginx
  service: name=nginx state=started enabled=yes
