pipeline {
    agent any
    environment {
        SUDO_PASS = credentials('sudo_pass')
    }
    stages {
        stage('Build') {
            steps {
                git branch: 'accu163', credentialsId: 'ssh_key_jenkins', url: 'git@github.com:TerebDan/DevOps-Trainee.git'
                dir('accu163') {
                    sh 'ansible-playbook accu163.yml --extra-vars "ansible_sudo_pass=${SUDO_PASS}" --skip-tags all'
                }
            }

            post {
                success {
                    sh 'echo "Build: all fine"'
                }
                failure {
                    sh 'echo "Build: fail"'
                }
            }
        }
        
        stage('Run Tests') {
            parallel {
                
                stage('Test the setup') {
                    steps {
                        sh 'echo "Setup test"'
                    }

                    post {
                        success {
                            sh 'echo "Test: all fine"'
                        }
        
                        failure {
                            sh 'echo "Test: error"'
                        }
                    }
                }
        
                stage('Test the application') {
                    steps {
                        sh 'echo "Application test"'
                    }
        
                    post {
                        success {
                            sh 'echo "Test: all fine"'
                        }
        
                        failure {
                            sh 'echo "Test: error"'
                        }
                    }
                }
            }
        }
    }
}

