pipeline {
    agent any
    environment {
        SUDO_PASS = credentials('sudo_pass')
    }
    stages {
        stage('Build') {
            steps {
                git branch: 'accu163', credentialsId: 'ssh_key_jenkins', url: 'git@github.com:TerebDan/DevOps-Trainee.git'
                dir('accu163') {
                    sh 'ansible-playbook accu163.yml --extra-vars "ansible_sudo_pass=${SUDO_PASS}"'
                }
            }

            post {
                success {
                    sh 'echo "Build: all fine"'
                }
                failure {
                    sh 'echo "Build: fail"'
                }
            }
        }
        
        stage('Run Tests') {
            parallel {
                
                stage('Test the setup') {
                    steps {
                        script {
                            try {
                                sh(script: "nmap 192.168.0.136 -p 80 | grep -o open", returnStdout: true)
                            } catch (Exception e) {
                                error("LB error")
                            }
                            
                            try {
                                sh(script: "nmap 192.168.0.140 -p 3306 | grep -o open", returnStdout: true)
                            } catch (Exception e) {
                                error("DB error")
                            }
                            
                            try {
                                sh(script: "nmap 192.168.0.141 -p 8000 | grep -o open", returnStdout: true)
                            } catch (Exception e) {
                                error("APP error")
                            }
                        }
                    }

                    post {
                        success {
                            sh 'echo "Setup test: all fine"'
                        }
        
                        failure {
                            sh 'echo "Setup test: error"'
                        }
                    }
                }
        
                stage('Test the application') {
                    steps {
                        script {
                            string status = sh(script: "curl -sLI -w '%{http_code}' http://192.168.0.136 \
                                -o /dev/null", returnStdout: true).trim()
                                
                            if (status != "200") {
                                error("index.html error")
                            }
                            
                            status = sh(script: "curl -sLI -w '%{http_code}' http://192.168.0.136/dbread \
                                -o /dev/null", returnStdout: true).trim()
                                
                            if (status != "200") {
                                error("dbread error")
                            }
                            
                            status = sh(script: "curl -sLI -w '%{http_code}' http://192.168.0.136/appserver \
                                -o /dev/null", returnStdout: true).trim()
                                
                            if (status != "200") {
                                error("appserver error")
                            }
                            
                            status = sh(script: "curl -sLI -w '%{http_code}' http://192.168.0.136/serverid \
                                -o /dev/null", returnStdout: true).trim()
                                
                            if (status != "200") {
                                error("serverid error")
                            }
                        }
                    }
        
                    post {
                        success {
                            sh 'echo "Application test: all fine"'
                        }
        
                        failure {
                            sh 'echo "Application test: error"'
                        }
                    }
                }
            }
        }
    }
}
